# LET'S START NUMPY PRACTICE

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(np.__version__)
type(arr)

[1 2 3 4 5 6 7 8 9]
1.24.1


numpy.ndarray

In [7]:
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2


In [15]:
%%timeit
my_arr = np.arange(1,100)+5
print(my_arr)


[  6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23
  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104]
[  6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23
  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104]
[  6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23
  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  53

In [14]:
%%timeit 
[i+5 for i in range(1,1000000)]

176 ms ± 16.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
x = np.random.randint(2,3)
print(x)

2


In [20]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.ndim)
print(a+5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [22]:
a = np.arange(27).reshape(3,3,3)
print(a.ndim)# number of dimension/rank 3D
print(a.shape)# number of axis in each dimension
print(a.size)# number elements
print(a)

3
(3, 3, 3)
27
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [25]:
a = np.random.randint(0,100,(5,4,4))
print(a)

[[[52 99 14 26]
  [44 49 23 75]
  [60 15 19 26]
  [92 46 62 76]]

 [[57 48 43 18]
  [39 23 62 40]
  [69  9 30 86]
  [90 14 13 21]]

 [[59 14  2 33]
  [85 99 52 69]
  [ 6 53 84  3]
  [97 25 69 39]]

 [[70 95 98 65]
  [50 24 55 68]
  [43 74 89 78]
  [64 31 73 64]]

 [[56 88 41  6]
  [86 33 63 72]
  [84 31 93 45]
  [39  8 55 80]]]


In [26]:
ashu = np.linspace(1,6,7)
print(ashu)

[1.         1.83333333 2.66666667 3.5        4.33333333 5.16666667
 6.        ]


In [5]:
import numpy as np
v = [[1,5,7],[6,4,9],[0,8,8]]
ar = np.array(v)
print(v)
ar.sum(axis=0)

[[1, 5, 7], [6, 4, 9], [0, 8, 8]]


array([ 7, 17, 24])

In [10]:
abc = np.array([32,5,76,65,99,4,0,70,44,10,21,26])
print(abc)
print(abc[1:6])
print(abc[3:])


[32  5 76 65 99  4  0 70 44 10 21 26]
[ 5 76 65 99  4]
[65 99  4  0 70 44 10 21 26]


In [12]:
var = np.array([[4,7,9,10,36],[22,15,66,1,77],[24,3,0,12,69]])
print(var)
print(var[1,1:4])

[[ 4  7  9 10 36]
 [22 15 66  1 77]
 [24  3  0 12 69]]
[15 66  1]
